# Generated by Django 5.1.1 on 2024-10-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_disaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='date_reported',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(),
        ),
    ]
