# Generated by Django 5.1.1 on 2024-10-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0003_alter_disaster_date_reported_alter_volunteer_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
